import streamlit as st, pandas as pd, numpy as np
from style import apply_style, hero, card, step
from mcdm_utils import CASE_DF, WEIGHT_DF, CRITERIA, WEIGHTS, show_case_intro, saw_calc, df_matrix, rank_df, download_workbook
st.set_page_config(page_title='SAW Method', layout='wide')
apply_style()
hero('02 | SAW: Simple Additive Weighting', 'Detailed English notes with proper equations, real case study, normalized matrix, weighted score, manual calculation example, interpretation and downloadable workbook.')
card('Core idea of SAW','<p>SAW assumes that the overall performance of an alternative can be represented by the weighted sum of normalized criterion values. Every criterion contributes additively to the final score. The alternative with the highest final score is selected as the best option.</p>','gold')
st.latex(r'S_i=\sum_{j=1}^{n}w_j r_{ij}')
st.latex(r'\text{Rank best alternative}=\max(S_i)')
card('Normalization formula','<p>SAW requires normalization because the criteria use different units such as USD, months, risk score and impact score.</p>','blue')
st.latex(r'r_{ij}=\frac{x_{ij}}{\max_i(x_{ij})}\quad \text{for benefit criteria}')
st.latex(r'r_{ij}=\frac{\min_i(x_{ij})}{x_{ij}}\quad \text{for cost criteria}')
show_case_intro()
R,S=saw_calc(); norm=df_matrix(R); rank=rank_df(S,'SAW Score')
st.subheader('Step 1: Normalized decision matrix')
st.dataframe(norm, use_container_width=True)
step('Manual example: A1 under cost criterion', 'Implementation Cost is a cost criterion, so the smallest cost is preferred. Minimum cost = 35,000. For A1, r = 35,000 / 42,000 = 0.833333.')
step('Manual example: A1 under benefit criterion', 'Expected Impact is a benefit criterion, so the highest impact is preferred. Maximum impact = 90. For A1, r = 82 / 90 = 0.911111.')
st.subheader('Step 2: Weighted normalized matrix')
weighted=pd.DataFrame(np.round(R*WEIGHTS,6), columns=CRITERIA, index=CASE_DF['Alternative']).reset_index()
st.dataframe(weighted, use_container_width=True)
st.latex(r'S_{A1}=0.22(0.833333)+0.30(0.911111)+0.20(1.000000)+0.15(0.750000)+0.13(0.857143)')
st.latex(r'S_{A1}=0.880096')
st.subheader('Step 3: Final SAW score and ranking')
st.dataframe(rank, use_container_width=True)
card('Interpretation','<p>The best alternative is the one with the highest SAW score. SAW is very transparent because every score can be traced back to normalized values and criterion weights. However, because it is additive, excellent performance in one criterion may compensate for weak performance in another criterion.</p>','green')
card('When SAW is suitable','<ul><li>When the decision maker needs a simple and explainable ranking.</li><li>When criteria are independent and compensation is acceptable.</li><li>When the purpose is teaching, dashboarding, preliminary screening, or simple project prioritization.</li></ul>','purple')
card('Limitations','<ul><li>Very sensitive to weights.</li><li>Assumes linear trade-off among criteria.</li><li>Does not measure distance from ideal solution.</li><li>Does not explicitly handle regret or compromise.</li></ul>','red')
download_workbook('saw_step_by_step_calculation.xlsx', {'Raw Data':CASE_DF,'Weights':WEIGHT_DF,'Normalized Matrix':norm,'Weighted Matrix':weighted,'Ranking':rank})
