import streamlit as st, pandas as pd, numpy as np
from style import apply_style, hero, card, step
from mcdm_utils import CASE_DF, WEIGHT_DF, CRITERIA, show_case_intro, topsis_calc, df_matrix, rank_df, download_workbook
st.set_page_config(page_title='TOPSIS Method', layout='wide')
apply_style()
hero('03 | TOPSIS: Technique for Order Preference by Similarity to Ideal Solution', 'A detailed TOPSIS lesson with proper equations, vector normalization, ideal solutions, distances, closeness coefficient and downloadable workbook.')
card('Core idea of TOPSIS','<p>TOPSIS selects the alternative that is closest to the Positive Ideal Solution and farthest from the Negative Ideal Solution. It is stronger than a simple summation method because it explicitly compares each alternative with the best and worst reference points.</p>','gold')
st.latex(r'r_{ij}=\frac{x_{ij}}{\sqrt{\sum_{i=1}^{m}x_{ij}^{2}}}')
st.latex(r'v_{ij}=w_j r_{ij}')
st.latex(r'D_i^+=\sqrt{\sum_{j=1}^{n}(v_{ij}-A_j^+)^2},\quad D_i^-=\sqrt{\sum_{j=1}^{n}(v_{ij}-A_j^-)^2}')
st.latex(r'CC_i=\frac{D_i^-}{D_i^+ + D_i^-}')
card('Ranking rule','<p>The best alternative has the highest closeness coefficient. A high value means the alternative is relatively close to the positive ideal and far from the negative ideal.</p>','blue')
show_case_intro()
R,V,Aplus,Aminus,Dp,Dm,C=topsis_calc()
norm=df_matrix(R); weighted=df_matrix(V)
ideal=pd.DataFrame({'Criterion':CRITERIA,'Type':['cost','benefit','benefit','cost','cost'],'Positive Ideal A+':np.round(Aplus,6),'Negative Ideal A-':np.round(Aminus,6)})
rank=pd.DataFrame({'Alternative':CASE_DF['Alternative'],'D+':np.round(Dp,6),'D-':np.round(Dm,6),'Closeness Coefficient':np.round(C,6)}).sort_values('Closeness Coefficient',ascending=False).reset_index(drop=True); rank['Rank']=range(1,len(rank)+1)
st.subheader('Step 1: Vector normalized matrix')
st.dataframe(norm, use_container_width=True)
step('Manual example: A1 cost normalization', 'For Implementation Cost, vector denominator = sqrt(42000² + 35000² + 50000² + 38000²). A1 normalized value is 42000 divided by that denominator.')
st.subheader('Step 2: Weighted normalized matrix')
st.dataframe(weighted, use_container_width=True)
st.subheader('Step 3: Positive and negative ideal solutions')
st.dataframe(ideal, use_container_width=True)
card('Important logic for ideal solution','<p>For benefit criteria, A+ is the maximum weighted normalized value and A- is the minimum. For cost criteria, A+ is the minimum weighted normalized value and A- is the maximum.</p>','purple')
st.subheader('Step 4: Distance and final closeness coefficient')
st.dataframe(rank, use_container_width=True)
st.latex(r'CC_{A1}=\frac{D_{A1}^-}{D_{A1}^+ + D_{A1}^-}')
card('Interpretation','<p>TOPSIS is excellent when the decision should be explained using the idea of closeness to an ideal solution. It is suitable for supplier selection, project evaluation, technology selection, university ranking, healthcare prioritization and sustainability assessment.</p>','green')
card('Limitations','<ul><li>Ranking can change if the normalization method changes.</li><li>It depends strongly on criterion weights.</li><li>It assumes criteria are monotonically increasing or decreasing.</li><li>It does not automatically solve inconsistent expert judgement.</li></ul>','red')
download_workbook('topsis_step_by_step_calculation.xlsx', {'Raw Data':CASE_DF,'Weights':WEIGHT_DF,'Vector Normalized':norm,'Weighted Normalized':weighted,'Ideal Solutions':ideal,'Ranking':rank})
