import streamlit as st, pandas as pd, numpy as np
from style import apply_style, hero, card, step
from mcdm_utils import download_workbook
st.set_page_config(page_title='AHP Method', layout='wide')
apply_style()
hero('04 | AHP: Analytic Hierarchy Process', 'A detailed AHP lesson for deriving criterion weights from expert judgement using pairwise comparison and consistency ratio.')
card('Core idea of AHP','<p>AHP is used when weights are obtained from expert judgement. Instead of asking experts to give direct weights, AHP asks them to compare criteria two at a time using a ratio scale. This is useful when decision makers can say one criterion is moderately or strongly more important than another.</p>','gold')
st.latex(r'A=[a_{ij}],\quad a_{ij}>0,\quad a_{ji}=\frac{1}{a_{ij}},\quad a_{ii}=1')
st.latex(r'w_i=\frac{\left(\prod_{j=1}^{n}a_{ij}\right)^{1/n}}{\sum_{i=1}^{n}\left(\prod_{j=1}^{n}a_{ij}\right)^{1/n}}')
st.latex(r'CI=\frac{\lambda_{\max}-n}{n-1},\quad CR=\frac{CI}{RI}')
card('Consistency rule','<p>A commonly used rule is that the pairwise comparison is acceptable when CR ≤ 0.10. If CR is too high, expert judgements should be reviewed because the comparisons may be inconsistent.</p>','blue')
criteria=['Cost','Impact','Feasibility','Time','Risk']
A=np.array([[1,1/3,1,2,2],[3,1,2,4,3],[1,1/2,1,3,2],[1/2,1/4,1/3,1,1/2],[1/2,1/3,1/2,2,1]],float)
pc=pd.DataFrame(np.round(A,4),columns=criteria,index=criteria).reset_index().rename(columns={'index':'Criterion'})
st.subheader('Real case: expert pairwise comparison for digital project criteria')
st.dataframe(pc, use_container_width=True)
step('How to read the table', 'The value 3 in row Impact and column Cost means Impact is judged to be moderately more important than Cost. The reciprocal value 1/3 appears in row Cost and column Impact.')
colsum=A.sum(axis=0); norm=A/colsum; weights=norm.mean(axis=1)
Aw=A@weights; lambdas=Aw/weights; lmax=lambdas.mean(); n=len(criteria); CI=(lmax-n)/(n-1); RI=1.12; CR=CI/RI
normdf=pd.DataFrame(np.round(norm,6),columns=criteria,index=criteria).reset_index().rename(columns={'index':'Criterion'})
wdf=pd.DataFrame({'Criterion':criteria,'AHP Weight':np.round(weights,6),'AHP Weight (%)':np.round(weights*100,2)})
cons=pd.DataFrame({'Measure':['lambda max','n','CI','RI','CR'],'Value':[round(lmax,6),n,round(CI,6),RI,round(CR,6)]})
st.subheader('Step 1: Column-normalized pairwise matrix')
st.dataframe(normdf, use_container_width=True)
st.subheader('Step 2: Priority vector / AHP weights')
st.dataframe(wdf, use_container_width=True)
st.latex(r'w_{Cost}=\frac{0.1667+0.1379+0.2069+0.1667+0.2353}{5}=0.1827\;\text{approximately}')
st.subheader('Step 3: Consistency check')
st.dataframe(cons, use_container_width=True)
if CR <= 0.10: st.success('The pairwise comparison is acceptable because CR ≤ 0.10.')
else: st.error('The pairwise comparison should be reviewed because CR > 0.10.')
card('Interpretation','<p>AHP does not rank alternatives by itself unless alternative comparisons are also included. In many practical MCDM studies, AHP is used to produce reliable weights, then those weights are used in SAW, TOPSIS, VIKOR or WASPAS.</p>','green')
card('Limitations','<ul><li>AHP becomes tiring when there are too many criteria.</li><li>Experts may give inconsistent judgements.</li><li>The 1–9 scale is subjective.</li><li>Group AHP requires careful aggregation of multiple experts.</li></ul>','red')
download_workbook('ahp_weight_calculation.xlsx', {'Pairwise Matrix':pc,'Normalized Matrix':normdf,'AHP Weights':wdf,'Consistency':cons})
