import streamlit as st, pandas as pd, numpy as np
from style import apply_style, hero, card, step
from mcdm_utils import CASE_DF, WEIGHT_DF, CRITERIA, show_case_intro, vikor_calc, df_matrix, download_workbook
st.set_page_config(page_title='VIKOR Method', layout='wide')
apply_style()
hero('05 | VIKOR: Compromise Ranking Method', 'A detailed VIKOR lesson explaining best/worst values, normalized gap, group utility S, individual regret R, compromise index Q, and downloadable calculation workbook.')
card('Core idea of VIKOR','<p>VIKOR is designed for decision problems with conflicting criteria. It does not simply search for the highest score. Instead, it identifies a compromise solution by balancing overall group utility and the worst individual regret.</p>','gold')
st.latex(r'S_i=\sum_{j=1}^{n}w_j\frac{f_j^*-f_{ij}}{f_j^*-f_j^-}')
st.latex(r'R_i=\max_j\left[w_j\frac{f_j^*-f_{ij}}{f_j^*-f_j^-}\right]')
st.latex(r'Q_i=v\frac{S_i-S^*}{S^- - S^*}+(1-v)\frac{R_i-R^*}{R^- - R^*}')
card('Ranking rule','<p>In VIKOR, a lower Q value is better. This is different from SAW, TOPSIS and WASPAS where a higher score is usually better.</p>','blue')
show_case_intro()
v=st.slider('VIKOR strategy parameter v',0.0,1.0,0.5,0.1)
fstar,fminus,gap,WG,S,R,Q=vikor_calc(v)
bestworst=pd.DataFrame({'Criterion':CRITERIA,'Best value f*':fstar,'Worst value f-':fminus})
gapdf=df_matrix(gap); wgdf=df_matrix(WG)
rank=pd.DataFrame({'Alternative':CASE_DF['Alternative'],'S group utility':np.round(S,6),'R individual regret':np.round(R,6),'Q compromise index':np.round(Q,6)}).sort_values('Q compromise index').reset_index(drop=True); rank['Rank']=range(1,len(rank)+1)
st.subheader('Step 1: Best and worst values')
st.dataframe(bestworst, use_container_width=True)
card('How best and worst are selected','<p>For benefit criteria, the best value is maximum and the worst value is minimum. For cost criteria, the best value is minimum and the worst value is maximum.</p>','purple')
st.subheader('Step 2: Normalized regret gap')
st.dataframe(gapdf, use_container_width=True)
step('Manual example: A1 cost gap', 'For Implementation Cost, best value = 35,000 and worst value = 50,000. A1 gap = (42,000 − 35,000) / (50,000 − 35,000) = 0.466667.')
st.subheader('Step 3: Weighted regret gap')
st.dataframe(wgdf, use_container_width=True)
st.subheader('Step 4: S, R and Q ranking')
st.dataframe(rank, use_container_width=True)
card('Interpretation','<p>S measures overall weakness across all criteria. R measures the largest single criterion weakness. Q combines both using the parameter v. When v = 0.5, the decision gives balanced attention to group utility and individual regret.</p>','green')
card('When VIKOR is suitable','<ul><li>Policy project prioritization.</li><li>Conflicting cost-impact-risk decisions.</li><li>Cases where the best option should be a compromise, not merely the highest weighted score.</li><li>Government or committee decisions involving multiple stakeholder interests.</li></ul>','blue')
card('Limitations','<ul><li>The interpretation of v must be justified.</li><li>Ranking direction is easy to confuse because lower Q is better.</li><li>Like other MCDM methods, results depend on weights and criterion selection.</li></ul>','red')
download_workbook('vikor_step_by_step_calculation.xlsx', {'Raw Data':CASE_DF,'Weights':WEIGHT_DF,'Best Worst':bestworst,'Gap Matrix':gapdf,'Weighted Gap':wgdf,'Ranking':rank})
