import streamlit as st, pandas as pd, numpy as np
from style import apply_style, hero, card, step
from mcdm_utils import CASE_DF, WEIGHT_DF, CRITERIA, show_case_intro, waspas_calc, df_matrix, download_workbook
st.set_page_config(page_title='WASPAS Method', layout='wide')
apply_style()
hero('06 | WASPAS: Weighted Aggregated Sum Product Assessment', 'A detailed WASPAS lesson combining weighted sum model and weighted product model with clear equations, calculation table and downloadable workbook.')
card('Core idea of WASPAS','<p>WASPAS combines two aggregation logics: the additive Weighted Sum Model and the multiplicative Weighted Product Model. The additive part rewards total performance. The product part penalizes alternatives that are very weak in any criterion.</p>','gold')
st.latex(r'Q_i^{(1)}=\sum_{j=1}^{n}w_j r_{ij}')
st.latex(r'Q_i^{(2)}=\prod_{j=1}^{n}(r_{ij})^{w_j}')
st.latex(r'Q_i=\lambda Q_i^{(1)}+(1-\lambda)Q_i^{(2)}')
card('Ranking rule','<p>The best alternative has the highest final WASPAS Q value. The parameter λ controls the balance between additive and multiplicative aggregation.</p>','blue')
show_case_intro()
lam=st.slider('WASPAS lambda λ',0.0,1.0,0.5,0.1)
R,Q1,Q2,Q=waspas_calc(lam)
norm=df_matrix(R)
rank=pd.DataFrame({'Alternative':CASE_DF['Alternative'],'Q1 Weighted Sum':np.round(Q1,6),'Q2 Weighted Product':np.round(Q2,6),'Final WASPAS Q':np.round(Q,6)}).sort_values('Final WASPAS Q',ascending=False).reset_index(drop=True); rank['Rank']=range(1,len(rank)+1)
st.subheader('Step 1: Normalized matrix')
st.dataframe(norm, use_container_width=True)
st.subheader('Step 2: WSM, WPM and final WASPAS score')
st.dataframe(rank, use_container_width=True)
st.latex(r'Q_{A1}^{(1)}=\sum w_jr_{A1j}=0.880096')
st.latex(r'Q_{A1}^{(2)}=\prod(r_{A1j})^{w_j}')
st.latex(r'Q_{A1}=0.5Q_{A1}^{(1)}+0.5Q_{A1}^{(2)}')
step('Why the product component matters', 'If an alternative has a very low normalized value for one important criterion, the product score will drop more sharply. This reduces the chance that one very strong criterion fully hides one very weak criterion.')
card('Interpretation','<p>WASPAS is useful when the decision maker wants a balance between total weighted performance and balanced performance across criteria. It is often used in supplier selection, green technology evaluation, AI model selection, project prioritization and sustainability studies.</p>','green')
card('Limitations','<ul><li>Requires positive normalized values for the product component.</li><li>The λ value should be justified or tested through sensitivity analysis.</li><li>Like SAW, it depends on the quality of normalization and weights.</li></ul>','red')
download_workbook('waspas_step_by_step_calculation.xlsx', {'Raw Data':CASE_DF,'Weights':WEIGHT_DF,'Normalized Matrix':norm,'Ranking':rank})
