import streamlit as st, pandas as pd
from style import apply_style, hero, card
from mcdm_utils import download_workbook
st.set_page_config(page_title='Real World Applications', layout='wide')
apply_style()
hero('07 | Real-World Applications of MCDM', 'Detailed examples showing how MCDM methods are used in education, government policy, healthcare, business, sustainability, AI and image processing.')
apps=pd.DataFrame({'Domain':['Higher Education','Healthcare','Government Policy','Business / Procurement','Sustainability / ESG','AI & Data Science','Image Processing','Smart City'],'Real Decision Problem':['Select digital transformation project','Prioritize hospital improvement initiatives','Rank public development projects','Select the best supplier','Choose renewable energy technology','Select best prediction or classification model','Rank denoising algorithms','Rank city infrastructure projects'],'Alternatives':['Projects or systems','Hospitals, treatments, interventions','Projects, districts, programmes','Suppliers or vendors','Solar, wind, biomass, hydro','Models or feature sets','Mean, Median, BM3D, NLM, proposed method','City zones or project packages'],'Criteria Examples':['Cost, impact, feasibility, time, risk','Effectiveness, cost, safety, accessibility, waiting time','Impact, cost, risk, readiness, sustainability','Price, quality, delivery, service, risk','Cost, emission, reliability, social acceptance','Accuracy, recall, runtime, interpretability, cost','PSNR, SSIM, MSE, runtime, visual quality','Congestion, safety, cost, resilience, citizen impact'],'Suitable Methods':['AHP-SAW, AHP-TOPSIS, VIKOR','AHP, TOPSIS, VIKOR','VIKOR, TOPSIS, WASPAS','AHP-TOPSIS, WASPAS','TOPSIS, VIKOR, WASPAS','WASPAS, TOPSIS','SAW, TOPSIS, WASPAS','AHP, TOPSIS, VIKOR']})
st.dataframe(apps,use_container_width=True)
card('Case 1: Scholarship selection','<p>Alternatives are applicants. Criteria may include CGPA, household income, interview score, leadership, co-curricular achievement and special hardship. CGPA is a benefit criterion, while household income may be treated as a cost criterion if the purpose is financial aid priority.</p>','gold')
card('Case 2: Image processing method ranking','<p>Alternatives are algorithms such as Mean Filter, Median Filter, Bilateral Filter, Non-Local Means, BM3D and a proposed method. PSNR and SSIM are benefit criteria. MSE and runtime are cost criteria. MCDM is useful because one algorithm may have high PSNR but poor runtime, while another may have better SSIM but slightly higher MSE.</p>','blue')
card('Case 3: Government project prioritization','<p>Alternatives are policy projects. Criteria include public impact, cost, implementation risk, time to completion, readiness and sustainability. VIKOR is suitable because government decisions usually require compromise between impact, budget and risk.</p>','green')
card('Case 4: AI model selection','<p>Alternatives are machine learning models. Criteria may include accuracy, F1-score, training time, inference time, interpretability and deployment cost. WASPAS is useful because a model with excellent accuracy but very poor runtime can be penalized by the product component.</p>','purple')
download_workbook('mcdm_real_world_applications.xlsx', {'Applications':apps})
