import streamlit as st, pandas as pd
from style import apply_style, hero, card, kpi
from mcdm_utils import CASE_DF, WEIGHT_DF, download_workbook
st.set_page_config(page_title='General MCDM Foundation', layout='wide')
apply_style()
hero('01 | General MCDM Foundation', 'A strong foundation before learning SAW, TOPSIS, AHP, VIKOR and WASPAS. This page explains decision matrix, criteria type, weights, normalization, ranking logic and common viva questions.')
cols=st.columns(4)
with cols[0]: kpi('Alternatives','4','Competing projects/options')
with cols[1]: kpi('Criteria','5','Cost and benefit criteria')
with cols[2]: kpi('Weights','Σw=1','Importance of criteria')
with cols[3]: kpi('Output','Rank','Transparent decision order')
card('What is MCDM?','<p><b>Multi-Criteria Decision-Making (MCDM)</b> is a structured mathematical approach for evaluating alternatives using several criteria at the same time. It is useful when no single criterion is enough to justify a decision. For example, a university should not choose a digital project only because it is cheap. It must also consider expected impact, feasibility, implementation time and risk.</p>','gold')
card('Basic MCDM structure','<p>A complete MCDM problem can be written as:</p>','blue')
st.latex(r'P=(A,C,W,X)')
card('Meaning of the notation','<ul><li><b>A</b> is the set of alternatives.</li><li><b>C</b> is the set of criteria.</li><li><b>W</b> is the vector of criterion weights.</li><li><b>X</b> is the decision matrix where each value x<sub>ij</sub> represents the performance of alternative i under criterion j.</li></ul>','purple')
st.subheader('Real case study used throughout this app')
st.dataframe(CASE_DF, use_container_width=True)
st.subheader('Criteria weight and type')
st.dataframe(WEIGHT_DF, use_container_width=True)
st.markdown('### Decision matrix notation')
st.latex(r'X=\left[x_{ij}\right]_{m\times n}=\begin{bmatrix}x_{11}&x_{12}&\cdots&x_{1n}\\x_{21}&x_{22}&\cdots&x_{2n}\\\vdots&\vdots&\ddots&\vdots\\x_{m1}&x_{m2}&\cdots&x_{mn}\end{bmatrix}')
st.latex(r'W=(w_1,w_2,\ldots,w_n),\quad \sum_{j=1}^{n}w_j=1,\quad w_j\ge 0')
card('Benefit vs cost criteria','<p><b>Benefit criterion:</b> a larger value is preferred, such as impact score, quality, safety or feasibility.</p><p><b>Cost criterion:</b> a smaller value is preferred, such as cost, time, risk, error rate or pollution.</p><p>This classification is critical. If a cost criterion is accidentally treated as a benefit criterion, the ranking can become misleading.</p>','red')
workflow=pd.DataFrame({'Step':[1,2,3,4,5,6,7,8,9,10],'Action':['Define decision objective','Identify alternatives','Select meaningful criteria','Classify benefit/cost criteria','Assign or calculate weights','Build decision matrix','Normalize values','Aggregate performance','Produce final ranking','Conduct sensitivity analysis'],'Why it matters':['Avoids unclear decision scope','Ensures comparable options','Prevents irrelevant indicators','Controls preference direction','Represents importance','Creates transparent raw input','Makes criteria comparable','Combines evidence and priority','Supports final decision','Checks robustness']})
st.subheader('Complete MCDM workflow')
st.dataframe(workflow, use_container_width=True)
card('Viva-safe explanation','<p>A safe explanation is: MCDM is used because the problem contains multiple conflicting criteria. The method converts different measurement scales into comparable normalized values, combines them with weights, and produces a ranking that is transparent and reproducible. The final ranking should be supported by sensitivity analysis, not accepted blindly.</p>','green')
download_workbook('general_mcdm_case_study.xlsx', {'Decision Matrix':CASE_DF,'Weights':WEIGHT_DF,'Workflow':workflow})
